let 
questions = [
    {
        num: 1,
        question: "¿Cómo te sientes?",
        op0: "Como un viejo cárdigan olbidado bajo alguna cama",
        op2: "Siento que no encajo",
        op5: "Como si el tiempo no avanzase",
        op7: "Como si regresara a casa tras un largo viaje",
        op10: "Siento frío, del tipo que empaña cristales",
        op15: "Tengo un mal presentimiento",
        op20: "Maravillada/o",
            options: [
                "Como si regresara a casa tras un largo viaje",
                "Maravillada/o",
                "Como un viejo cárdigan olbidado bajo alguna cama",
                "Siento frío, del tipo que empaña cristales",
                "Como si el tiempo no avanzase",
                "Tengo un mal presentimiento",
                "Siento que no encajo",
            ],
    },

    {
        num: 2,
        question: "Elige un momento y lugar",
        op0: "Bailando bajo la luz de las farolas con sabor a alcohol en los labios, tacones altos resonando sobre adoquines",
        op2: "Un lago, donde los poetas van a poner fin a sus días, parece un lugar perfecto para llorar",
        op5: "Bailando en la cocina, bajo la tenue luz de la nevera",
        op7: "Suenan campanadas en la iglesia, el arroz cubriendo el suelo parece nieve",
        op10: "El camino no tomado que, por alguna razón, ahora te llama a seguirle",
        op15: "Una habitación en llamas",
        op20: "El cansado, viejo y solitario sitio de siempre",
        options: [
            "Un lago, donde los poetas van a poner fin a sus días, parece un lugar perfecto para llorar",
            "Suenan campanadas en la iglesia, el arroz cubriendo el suelo parece nieve",
            "El camino no tomado que, por alguna razón, ahora te llama a seguirle",
            "El cansado, viejo y solitario sitio de siempre",
            "Una habitación en llamas",
            "Bailando bajo la luz de las farolas con sabor a alcohol en los labios, tacones altos resonando sobre adoquines",
            "Bailando en la cocina, bajo la tenue luz de la nevera",
        ],
    },

    {
        num: 3,
        question: "Elige algo para llevar contigo",
        op0: "Pintalabios negro y una camiseta vintage",
        op2: "Una rosa roja, que floreció sobre suelo helado",
        op5: "Una bufanda vieja, olvidada en algún lugar",
        op7: "Un único guante extrañando a su pareja",
        op10: "Perfume barato que parece no llegar a desvanecerse nunca",
        op15: "Un medallón invisible con la foto de una sonrisa",
        op20: "Notas pasadas en secreto, escritas sobre papel de libreta",
        options: [
            "Una rosa roja, que floreció sobre suelo helado",
            "Una bufanda vieja, olvidada en algún lugar",
            "Pintalabios negro y una camiseta vintage",
            "Un único guante extrañando a su pareja",
            "Un medallón invisible con la foto de una sonrisa",
            "Notas pasadas en secreto, escritas sobre papel de libreta",
            "Perfume barato que parece no llegar a desvanecerse nunca",
        ],
        
    },

    {
        num: 4,
        question: "¿Qué es lo que quieres ahora mismo?",
        op0: "Ser capaz de poder cambiar el final",
        op2: "Auroras y prosa triste",
        op5: "Poder olvidar",
        op7: "Atardeceres color rosa y azul, sin toque de queda",
        op10: "Dormir hasta mediodía aunque sea solo para recordar los viejos tiempos",
        op15: "Bailar al son del hablar de la gente",
        op20: "Volver a ver a cierta persona",
        options: [
            "Auroras y prosa triste",
            "Atardeceres color rosa y azul, sin toque de queda",
            "Ser capaz de poder cambiar el final",
            "Bailar al son del hablar de la gente",
            "Volver a ver a cierta persona",
            "Poder olvidar",
            "Dormir hasta mediodía aunque sea solo para recordar los viejos tiempos",
        ],
    },

    {
        num: 5,
        question: "¿Qué es aquello que siempre llevas contigo?",
        op0: "Sombras en la cola del supermercado que nunca llego a alcanzar",
        op2: "A mi musa e inspiración",
        op5: "Mis recuerdos y la certeza de haber estado allí",
        op7: "Un amigo o amiga y una lista con 20 preguntas",
        op10: "Un corazón roto",
        op15: "Un desastre, pero el desastre que querías",
        op20: "Una pregunta que nunca llega a desvanecerse",
        options: [
            "Mis recuerdos y la certeza de haber estado allí",
            "Un amigo o amiga y una lista con 20 preguntas",
            "Un desastre, pero el desastre que querías",
            "Una pregunta que nunca llega a desvanecerse",
            "Sombras en la cola del supermercado que nunca llego a alcanzar",
            "Un corazón roto",
            "A mi musa e inspiración",
        ],
    },

    {
        num: 6,
        question: "Y, finalmente, ¿qué es lo que has dejado atrás?",
        op0: "El persistente olor a tabaco",
        op2: "Todos estos cínicos clones",
        op5: "Un viejo álbum de fotos y mejillas ruborizadas",
        op7: "Una nota de papel y noches en tiendas de campaña",
        op10: "La cama más cálida que has conocido nunca",
        op15: "Profundos miedos y la cuerda atando tus manos",
        op20: "Palabras nunca pronunciadas que se perdieron en tu garganta",
        options: [
            "Un viejo álbum de fotos y mejillas ruborizadas",
            "Una nota de papel y noches en tiendas de campaña",
            "El persistente olor a tabaco",
            "La cama más cálida que has conocido nunca",
            "Palabras nunca pronunciadas que se perdieron en tu garganta",
            "Profundos miedos y la cuerda atando tus manos",
            "Todos estos cínicos clones",
        ],

    },
]